### ISSUE TITLE
Plans to support the new api?

### ISSUE THREAD

**Issue by SaschaDeWaal** [fvdm/nodejs-ns-api#18]
The ns has a new api. The old one (that this module uses) will be turned off on 1 Oct 2019.
Are there plans to support this new api? Or is it better if I start to use a other way?

Thanks
https://apiportal.ns.nl/

**Comment by fvdm** [comment]
Hi @SaschaDeWaal, yes I'm rewriting the package for the new NS API and modernize the code with promises and stuff.

**Comment by SaschaDeWaal** [comment]
Thanks a lot @fvdm!

**Comment by qistoph** [comment]
@fvdm anything I can do to help?

I would be interested to use your package in my MagicMirror module [MMM-nstreinen](https://github.com/qistoph/MMM-nstreinen).

**Comment by fvdm** [comment]
@qistoph Cool! Not that I know for now. I’m writing the new lib and will publish a beta soon.

At first I wanted to make it more like a API wrapper so that it can be more fluid with changes at NS. But there are quiet some consistency problems and very incomplete docs, so now I rather design it for interface stability instead of less maintenance.

**Comment by fvdm** [comment]
Hey @SaschaDeWaal & @qistoph, I have uploaded the new code to the v3 branch. As far as I can test right now it should work, but be aware this is not yet safe for production. Would be great if you could test it.

https://github.com/fvdm/nodejs-ns-api/tree/v3

**Comment by qistoph** [comment]
Got to implement your module in my project. I'm using `getStations`, `getTrips` and `getDepartures` and it looks good to me.

I did find some issues with lack of documentation and requirement for station codes. Below is the email I've sent to NS:

> Beste NS,
> 
> Bedankt voor het informeren over de nieuwe NS API. Ik ben inmiddels aan de slag gegaan om mijn MagicMirror module aan te passen zodat deze met de nieuwe API werkt. Daarbij doe ik een aantal bevindingen die ik graag met jullie deel. Hopelijk helpt dit jullie de API (documentatie) nog verder te verbeteren.
> 
> **De documentatie van de NS Travel Information is wat karig.**
> In de documentatie is geen beschrijving te vinden van de bedoeling van een functie. De namen zijn in veel gevallen vanzelf sprekend, maar het verschil tussen getDepartures en getBigDepartures is mij nog niet duidelijk.
> 
> Ook ontbreekt in de documentatie een beschrijving van het resultaat van functies en de daarin te verwachten velden en waardes. Inmiddels heb ik gezien dat getDepartures soms bijvoorbeeld een optie 'messages' bevat die in de documentatie niet beschreven is.
> 
> Verder ben ik erg zoekende wat ik, met name bij verstoring van treinverkeer, kan verwachten van de verschillende functies. Komen ritten die uitvallen nog voor in de resultaten van getDepartures en getTrips en hoe zijn die dan te onderscheiden van niet uitgevallen ritten?
> 
> **getDepartures station alleen op code.**
> De aanroep van getDepartures werkt niet met de volledige naam van een station, maar alleen met een NS station-code. Dit in tegenstelling tot getTrips. Het zou mooi zijn als de getDepartures ook zou werken met de naam van een station.

**Comment by qistoph** [comment]
FYI, I got an e-mail from NS:

> Hartelijk bedankt voor je interesse in de NS API. We zijn afgelopen half jaar overgestapt naar het API Portal waar je een abonnement hebt op de "Public-Travel-Information".
Door wat interne verschuivingen die we toen nog niet in beeld hadden is er nu nog een kleine wijziging die afnemers moeten gaan doorvoeren.
> 
> Indien je gebruik wilt blijven maken van de mogelijkheid om reisinformatie op te vragen, moeten de volgende wijzigingen gedaan worden:
> 
>     - Ga naar het API portal: https://apiportal.ns.nl/
>     - Meld je daar aan met het account dat je al eerder hebt aangemaakt
>     - Zoek het product "NsApp" en abonneer je op dit product
>     - Er wordt een nieuwe API key aangemaakt die je dient te gaan gebruiken.
>     - De endpoints veranderen van https://gateway.apiportal.ns.nl/public-reisinformatie/ naar https://gateway.apiportal.ns.nl/reisinformatie-api alle parameters in de url blijven ongewijzigd.

The API endpoints probably need to be updated in your code too.

**Comment by fvdm** [comment]
@qistoph I got the same mail. I'm working on it right away, it needs to be released asap.

**Comment by fvdm** [comment]
Hey guys, I'm finally close to release. Sorry for the massive delay, I have very little room in my agenda. I push the release when the readme is in line with the code. The methods `getInternationalPrice` and `getExitSide` come later, because I can't get them to work.

**Comment by fvdm** [comment]
I pushed v4 to npm. Yeah I know wrong version.. my release script didn't process the major release properly so the already set 3.0.0 in the package.json became 4.0.0 and that was auto pushed. 😛 I didn't want to overwrite the public repo.

Anyway, it is done. The two mentioned methods will come later and I'm looking into the other APIs that are available.
