### ISSUE TITLE
Uitschakelen van oude disruptions API vanaf 4 augustus 2021

### ISSUE THREAD

**Issue by qistoph** [fvdm/nodejs-ns-api#24]
From their email:

(For English, see below)

Goedendag,

Vanuit NS zijn we continu bezig met het verbeteren van onze APIs. Daarom willen we u erop attenderen dat in onze reisinformatie-api versie 2 van de disruptions endpoints vanaf 4 augustus 2021 uitgeschakeld zal worden. Het gaat om de volgende endpoints:

https://gateway.apiportal.ns.nl/reisinformatie-api/api/v2/disruptions
https://gateway.apiportal.ns.nl/reisinformatie-api/api/v2/disruptions/{id}
https://gateway.apiportal.ns.nl/reisinformatie-api/api/v2/disruptions/station/{stationCode}

Deze endpoints worden vervangen door de volgende v3 endpoints:

https://gateway.apiportal.ns.nl/reisinformatie-api/api/v3/disruptions
https://gateway.apiportal.ns.nl/reisinformatie-api/api/v3/disruptions/{type}/{id}
https://gateway.apiportal.ns.nl/reisinformatie-api/api/v3/disruptions/station/{stationCode}

Deze nieuwe endpoints zijn nu al beschikbaar. We raden daarom aan om zo snel mogelijk te migreren naar deze nieuwe endpoints. De andere endpoints in de reisinformatie-api blijven gewoon werken, zoals ze nu ook al doen.

De reden voor het introduceren van het nieuwe endpoint is het feit dat verstoringen en werkzaamheden nu opgedeeld kunnen worden in meerdere tijdvakken. Er kunnen bijvoorbeeld werkzaamheden plaatsvinden in een weekend, waarbij de maatregelen op zaterdag anders zijn dan die op zondag. In het oude endpoint werd dit alleen in de tekst vermeld. In het nieuwe endpoint zullen er voor deze werkzaamheid meerdere tijdvakken worden teruggegeven.Daarnaast zijn de velden in de response meer consistent gemaakt. Let op bij het migreren naar de nieuwe URL dat er door deze wijzigingen wel aanpassingen zitten in het response object. Een voorbeeld van een response is te vinden in de bijlage.

Meer informatie vindt u op het API portaal. Mochten er nog vragen zijn voor het migreren dan horen we dat graag.

Groeten,

NS MLab

----------------------------------

Dear reader,

As NS we are continuously working on improving our APIs. In that light, we want to announce the deprecation of some of our endpoints. As of August 4 2021 we will no longer support version 2 of our disruptions endpoints in our travel information api (reisinformatie-api). These deprecated endpoints include:

https://gateway.apiportal.ns.nl/reisinformatie-api/api/v2/disruptions
https://gateway.apiportal.ns.nl/reisinformatie-api/api/v2/disruptions/{id}
https://gateway.apiportal.ns.nl/reisinformatie-api/api/v2/disruptions/station/{stationCode}

These endpoints are being replaced by the following new endpoints:

https://gateway.apiportal.ns.nl/reisinformatie-api/api/v3/disruptions
https://gateway.apiportal.ns.nl/reisinformatie-api/api/v3/disruptions/{type}/{id}
https://gateway.apiportal.ns.nl/reisinformatie-api/api/v3/disruptions/station/{stationCode}

 

These new endpoints are already available. We recommend to migrate to these new endpoints as soon as possible. All other endpoints in the travel information api will remain the same.

 

The reason for the introduction of a new endpoint lies in the fact that the structure of the data for disruptions and maintenance has changed. They can now be divided into multiple timespans. For example, maintenance in a weekend could have consequences on Saturday, which are different from the consequences on Sunday. The old endpoint returned this information only in text. The new endpoint will return multiple timespans for such a situation. Apart from these changes, the fields in the response have been updated to be more consistent. Because of these changes, the response object has changed. An example of the new format can be found in the attached json file.

For more information, please check the API documentation on the API portal. If there are any questions remaining, please let us know.

Kind regards,

NS MLab

**Comment by qistoph** [comment]
This API is in use in the module:
https://github.com/fvdm/nodejs-ns-api/blob/5f9b5ea8f832a1ce335bb602e369ac5425ceffde/nsapi.js#L187

**Comment by fvdm** [comment]
Hi @qistoph, thanks! I'll check it out when I have time.

**Comment by fvdm** [comment]
This is resolved. I will publish an update to NPM tomorrow.
