### ISSUE TITLE
Response error: API_KEY_NOT_ALLOWED_TO_PLAN_DOOR_TO_DOOR 

### ISSUE THREAD

**Issue by gevgeny** [fvdm/nodejs-ns-api#26]
Trying to use some of the lib's methods like `getAllStations` all `getTrips`, but get this: error

```json
{
    "timestamp": "2021-05-08T08:27:36+0000",
    "path": "/api/v3/trips",
    "message": "Bad Request",
    "requestId": "6bbad54b-db8c-43e0-8f33-844f3eec3dc6",
    "code": 400,
    "errors": [
        {
            "message": "Met deze API key mogen geen deur-tot-deur adviezen opgevraagd worden 🙁",
            "type": "API_KEY_NOT_ALLOWED_TO_PLAN_DOOR_TO_DOOR",
            "lang": "nl"
        }
    ]
}
```

This is strange because this key works with `https://gateway.apiportal.ns.nl/places-api/v2/places` api. 
Any ideas?

**Comment by fvdm** [comment]
I believe you need to add the 'NS App' product to your API account. It's been a while since I created my account, but I remember needing to sign up to different products to access certain endpoints.

https://apiportal.ns.nl/products/NsApp

**Comment by gevgeny** [comment]
@fvdm hmm. I think it is already added.
![image](https://user-images.githubusercontent.com/1986803/117537245-f82aae00-afff-11eb-93db-96a4db087c53.png)
And my profile: 
![image](https://user-images.githubusercontent.com/1986803/117537274-20b2a800-b000-11eb-8089-8ce22f4c6853.png)

**Comment by fvdm** [comment]
Alright, I will check it out and add the Places API in the process.

**Comment by gevgeny** [comment]
I tried to make the call via vanilla api (https://gateway.apiportal.ns.nl/reisinformatie-api/api/v3/trips) and responses with the same error, so looks like it is not the lib issue, or I am doing something wrong :)

**Comment by gevgeny** [comment]
Sure. 
```
https://gateway.apiportal.ns.nl/reisinformatie-api/api/v3/trips?
destinationLat=52.0413726539037&
destinationLng=4.34035386746875&
dateTime=2021-05-07T18:35:00&
originLat=52.3568339514312&
originLng=4.82095942954253
```

I tried to add names but it does not help: 
```
https://gateway.apiportal.ns.nl/reisinformatie-api/api/v3/trips?
destinationLat=52.0413726539037&
destinationLng=4.34035386746875&
dateTime=2021-05-07T18:35:00&
originLat=52.3568339514312&
originLng=4.82095942954253&
destinationName=Patentlaan 1, 2288EE, Rijswijk&
originName=Jan Muschstraat, Amsterdam
```

**Comment by fvdm** [comment]
The names are for your own reference to be included in the response. They have no effect on the query.

I get the same error when I use the coordinates. It works fine when I use `fromStation` and `toStation`. I think the more detailed routes need a different subscription. To find out more I have send them an email.

**Comment by gevgeny** [comment]
Thanks!

**Comment by fvdm** [comment]
Hi @gevgeny, I got a reply from NS. Door-to-door access is not yet available to external developers.

Until it is I think the [Google Maps Directions API](https://developers.google.com/maps/documentation/directions/get-directions#TravelModes) with the `mode=transit` parameter is better suited for this.

**Comment by gevgeny** [comment]
Hi @gevgeny. Got the response too, not available for users.
